# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'figChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for figChat
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'figChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'figChat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for figChat-tvOS
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'figChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
